{% set name = "jid" %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/simeji/jid/archive/v{{ version }}.tar.gz
  sha256: 0912050b3be3760804afaf7ecd6b42bfe79e7160066587fbc0afa5324b03fb48

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - jid --help

about:
  home: https://github.com/simeji/jid
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Json incremental digger
  dev_url: https://github.com/simeji/jid

extra:
  recipe-maintainers:
    - danielnachun
