schema_version: 1

context:
  version: "1.1.1"

package:
  name: jid
  version: ${{ version }}

source:
  url: https://github.com/simeji/jid/archive/v${{ version }}.tar.gz
  sha256: 5f4c200625f0a1eb7a1bdb5578693fa30fbc935eb66608c9bb6d7aef90566bd8

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - jid --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Json incremental digger
  homepage: https://github.com/simeji/jid
  repository: https://github.com/simeji/jid

extra:
  recipe-maintainers:
    - danielnachun
