schema_version: 1

context:
  version: "1.0.0"

package:
  name: jid
  version: ${{ version }}

source:
  url: https://github.com/simeji/jid/archive/v${{ version }}.tar.gz
  sha256: 93eba44a69e570ecfe6c99c311568f446cddfe1ddd99672fc49fc0df3cbcdab7

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - jid --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Json incremental digger
  homepage: https://github.com/simeji/jid
  repository: https://github.com/simeji/jid

extra:
  recipe-maintainers:
    - danielnachun
